language: php

php:
    - 7.3
    - 7.4
    
sudo: false

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - sudo apt-get install nodejs --yes
    - npm install
    - npm ls
    - composer install

script:
    - composer integrate
